name: 测试模板
description: 模板简介
title: "[标题] "
labels: ["标签"]
body:
  - type: input
    id: input_id
    attributes:
      label: 测试：文本框提示
      description: |
        测试：文本框下方灰字提示
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: 测试：其他文本输入
      description: |
        其他文本
    validations:
      required: false
